employee/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, re_path
from employee import views

app_name = "employee"
urlpatterns = [

    re_path(
       r'^list/$',
       views.EmployeeListView.as_view(),
       name='list'
    ),

    # URL pattern for the UserUpdateView
    re_path(
        r'^add/$',
        views.EmployeeCreateView.as_view(),
        name='add'
    ),

    re_path(
        r'^delete/(?P<pk>\d+)/$',
        views.EmployeeDeleteView.as_view(),
        name='delete'
    ),

   re_path(
        r'^~update/$',
        views.EmployeeProfileUpdateView.as_view(),
        name='profile_update'
    ),
    re_path(
        r'^me/$',
        views.EmployeeProfileDetailView.as_view(),
        name='profile_detail'
    ),
    re_path(
        r'^invite/$',
        views.InvitationCreateView.as_view(),
        name='invite'
    ),

]

vetted/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found
from .views import HomeView, DashboardView

urlpatterns = [
    path('',HomeView.as_view(),name="home"),
    path('dashboard',DashboardView.as_view(),name="dashboard"),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('u/', include("users.urls", namespace="users")),
    path('company/', include("company.urls", namespace="company")),
    path('employee/', include("employee.urls", namespace="employee")),

]

employee/models.py
from django.db import models
from django.core import mail
from django.dispatch import receiver

from allauth.account.signals import user_signed_up

from vetted.models import  DateTimeStampedModel


class Employee(DateTimeStampedModel):
    name = models.CharField(max_length=255,blank=True)
    about_me = models.TextField(blank=True)
    user = models.OneToOneField("users.User",null=True, on_delete=models.CASCADE) #models.SET_NULL not required
    company = models.ForeignKey("company.Company",null=True,on_delete= models.CASCADE)
    created_by = models.ForeignKey("users.User",null=True,on_delete= models.CASCADE,related_name="company_admin")

    def save(self,*args,**kwargs):
        """
        :param args:
        :param kwargs:
        :return:  update user role with that of employee in first creation
        """
        if not self.pk:
            self.user.role = "3"
            self.user.save()
        return super(Employee,self).save(*args,**kwargs)


class Invitation(DateTimeStampedModel):
    company = models.ForeignKey("company.Company", null=True, on_delete=models.CASCADE)
    sent_by = models.ForeignKey("users.User",on_delete=models.CASCADE,related_name="invited_by")
    email = models.EmailField(unique=True)

    def save(self,*args,**kwargs):
        send_mail=mail.send_mail("You are invited to join vetted","","Vetted invitation <noreply@vetted.com>",[self.email],html_message='')
        super(Invitation,self).save(*args,**kwargs)

@receiver(user_signed_up)
def user_signed_up_(request,user,**kwargs):
    """
    :param request:
    :param user:
    :param kwargs:
    :return:
    Delete the invitation object if sent any and assign employee and company to user
    """
    try:
        inv_obj = Invitation.objects.get(email=user.email)
        Employee.objects.create(user=user,company= inv_obj.company, created_by=inv_obj.sent_by)
        user.role = "3"
        user.save()
        inv_obj.delete()
    except Exception as e:
        print(e)

employee/forms.py
from django import forms

from .models import Employee, Invitation
from users.models import User

class EmployeeForm(forms.ModelForm):
    email = forms.EmailField(required=True)

    def __init__(self,*args,**kwargs):
        self.request = kwargs.pop("request")
        super(EmployeeForm, self).__init__(*args,**kwargs)

    def clean_email(self):
        """
        :return: Raise validation error if created employee email domain does'nt match with it's creator company email domain.
        """
        email = self.cleaned_data["email"]
        #check if email already associated
        try:
            u=User.objects.get(email=email)
        except:
            raise forms.ValidationError("The user does'nt exist with this email, please invite him")

        if self.request.user.company.email_domain != email.split("@")[1]:
            raise forms.ValidationError("Company domain must match with email domain i.e. "+self.request.user.company.email_domain)
        return email

    class Meta:
        model = Employee
        fields = ("name","email")

    # def save(self):
    #     email=self.cleaned_data['email']
    #     self.user = User.objects.get(email=email)
    #     return super(EmployeeForm, self).save()


class EmployeeProfileForm(forms.ModelForm):
    """
    return: This form is for employee profile edit only.
    """
    class Meta:
        model =  Employee
        fields = ("name","about_me")

class InvitationForm(forms.ModelForm):

    def __init__(self,*args,**kwargs):
        self.request = kwargs.pop("request")
        super(InvitationForm, self).__init__(*args,**kwargs)

    def clean_email(self):
        """
        :return: Invitaion created only when it's email domain match with creator's company email domain
        """
        email = self.cleaned_data["email"]
        user=User.objects.filter(email=email)
        if user:
            raise forms.ValidationError("User with this email already exist.")
        if self.request.user.company.email_domain != email.split("@")[1]:
            raise forms.ValidationError("Company domain must match with email domain i.e. " + self.request.user.company.email_domain)
        return email

    class Meta:
        model = Invitation
        fields = ("email",)

employee/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from django.urls import reverse
from django.http import Http404
from django.contrib import messages

from .models import Employee, Invitation
from .forms import EmployeeForm, EmployeeProfileForm, InvitationForm
from users.models import User

from django.contrib.auth.mixins import LoginRequiredMixin
from vetted.mixins import CompanyAdminMixin, RequestFormKwargsMixin


class EmployeeListView(CompanyAdminMixin,ListView):
    model = Employee
    paginate_by = 10

    def get_queryset(self):
        return Employee.objects.filter(company = self.request.user.company)

class EmployeeCreateView(CompanyAdminMixin, RequestFormKwargsMixin, CreateView):
    model = Employee
    form_class = EmployeeForm

    def get_success_url(self):
        return reverse('employee:list')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.company = self.request.user.company
        form.instance.user  = User.objects.get(email=form.data["email"])
        return super(EmployeeCreateView, self).form_valid(form)


class EmployeeDeleteView(CompanyAdminMixin, DeleteView):

    def get_object(self,*args,**kwargs):
        pk = self.kwargs["pk"]
        try:
            object = Employee.objects.get(pk=pk,company=self.request.user.company)
        except:
            raise Http404
        return object

    def get_success_url(self):
        return reverse('employee:list')

class EmployeeProfileUpdateView(LoginRequiredMixin,UpdateView):
    form_class = EmployeeProfileForm
    model = Employee
    template_name ="employee/employee_profile_form.html"

    def get_success_url(self):
        return reverse("home")

    def get_object(self, *args, **kwargs):
        return Employee.objects.get(user=self.request.user)

class EmployeeProfileDetailView(LoginRequiredMixin,DetailView):
    model = Employee
    template_name ="employee/employee_profile_detail.html"

    def get_success_url(self):
        return reverse("employee:detail")

    def get_object(self, *args, **kwargs):
        return Employee.objects.get(user=self.request.user)

class InvitationCreateView(CompanyAdminMixin, RequestFormKwargsMixin, CreateView):
    model = Invitation
    form_class = InvitationForm

    def get_success_url(self):
        messages.success(self.request,"Invitation mail sent on console")
        return reverse('employee:invite')

    def form_valid(self, form):
        form.instance.sent_by = self.request.user
        form.instance.company = self.request.user.company
        return super(InvitationCreateView, self).form_valid(form)

templates/employee/employee_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h4>Add Employee</h4>
   <form method="post" action="{% url 'employee:add' %}">
       {% csrf_token %}
{{form | crispy }}
       <input type="submit" class="btn btn-sm">
       </form>


{% endblock %}

templates/employee/employee_list.html
{% extends "base.html" %}

{% block content %}


<div class="row">
    <div class="col-lg-3">
        <b>Name</b>
    </div>
    <div class="col-lg-3">
        <b>Email</b>
    </div>
    <div class="col-lg-3">
       <b>Delete</b>
    </div>
</div>
<br/>

{% for employee in object_list %}

<div class="row">
    <div class="col-lg-3">
        {{employee.name | upper}}
    </div>
    <div class="col-lg-3">
        {{employee.user.email}}
    </div>
    <div class="col-lg-3">
        <form method="post" action="{% url 'employee:delete' pk=employee.pk %}">
            {% csrf_token %}
            <input type="submit"  class="btn btn-sm btn-danger" value="del">
        </form>

    </div>
</div>

    <div style="margin-top:10px;border-top: 1px dotted gray" class="row">
        &nbsp;
    </div>
{% endfor %}

<div class="row">

    {% include 'pagination.html' %}
</div>
{% endblock %}

templates/employee/employee_profile_detail.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-lg-6">
    <table cellpadding="10px">
        <tr>
            <td><b>Email: </b></td>
            <td>&nbsp;&nbsp;</td>
            <td>{{request.user.email}}</td>
        </tr>
          <tr>
            <td><b>Name: </b></td>
            <td>&nbsp;&nbsp;</td>
            <td>{{object.name}}</td>
        </tr>

         <tr>
            <td><b>About: </b></td>
            <td>&nbsp;&nbsp;</td>
            <td>{{object.about_me}}</td>
        </tr>

         <tr>
            <td><b>Company: </b></td>
            <td>&nbsp;&nbsp;</td>
            <td>{{object.company.name}}</td>
        </tr>
    </table>
</div>
</div>
{% endblock %}

templates/employee/employee_profile_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h4>Edit profile</h4>


   <form method="post" action="{% url 'employee:profile_update' %}">
       {% csrf_token %}
{{form | crispy }}
       <input type="submit" class="btn btn-sm">
       </form>

{% endblock %}

templates/employee/invitation_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% if messages %}
{% for message in messages %}
<span style="color:green">{{message}}</span>
{% endfor %}

{% endif %}

<h4>Invite Employee</h4>
   <form method="post" action="{% url 'employee:invite' %}">
       {% csrf_token %}
{{form | crispy }}
       <input type="submit" class="btn btn-sm">
       </form>


{% endblock %}