company/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, re_path
from company import views

app_name = "company"
urlpatterns = [

    re_path(
       r'^list/$',
       views.CompanyListView.as_view(),
       name='list'
    ),

    # URL pattern for the UserUpdateView
    re_path(
        r'^add/$',
        views.CompanyCreateView.as_view(),
        name='add'
    ),

    re_path(
        r'^delete/(?P<pk>\d+)/$',
        views.CompanyDeleteView.as_view(),
        name='delete'
    ),


]

vetted/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found
from .views import HomeView, DashboardView

urlpatterns = [
    path('',HomeView.as_view(),name="home"),
    path('dashboard',DashboardView.as_view(),name="dashboard"),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('u/', include("users.urls", namespace="users")),
    path('company/', include("company.urls", namespace="company")),
    path('employee/', include("employee.urls", namespace="employee")),

]

company/models.py
from django.db import models

from users.models import  User
from vetted.models import DateTimeStampedModel
# Create your models here.

class Company(DateTimeStampedModel):
    name = models.CharField(max_length=255,blank=True)
    email_domain = models.CharField(max_length=255,unique=True)
    admin = models.EmailField(max_length=255,unique=True)
    created_by = models.ForeignKey("users.User",on_delete=models.CASCADE,related_name="created_by")
    created_for = models.ForeignKey("users.User",on_delete=models.CASCADE,related_name="created_for")

    def save(self,*args,**kwargs):
        u=User.objects.filter(email=self.admin)
        u.update(role="2")
        self.created_for=u.first()
        super(Company,self).save(*args,**kwargs)

company/forms.py
import validators

from django import forms

from .models import Company
from users.models import User

class CompanyForm(forms.ModelForm):
    """
    return: The company creation form used by overalladmin to create new company
    """

    def clean_domain(self):
        """
        :return: The email_domain is to restrict user assignment within the organisation's email namespace. In future
        company will be active only when admin verify it's email_domain
        """
        domain=self.cleaned_data['email_domain']
        flag = validators.domain(domain)
        if flag == True:
            return domain
        else:
            raise forms.ValidationError("Domain must be like google.com,sites.google.com, etc")

    def clean_admin(self):
        """
        :return: Only signed up user can be assigned an admin role for any company
        """
        email = self.cleaned_data["admin"]
        try:
            User.objects.get(email=email)
        except:
            raise forms.ValidationError("User with this email never signed up")
        return email


    class Meta:
        model = Company
        fields = ("name","email_domain","admin")

company/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DeleteView
from django.urls import reverse
from django.http import Http404

from .models import Company
from .forms import CompanyForm

from django.contrib.auth.mixins import LoginRequiredMixin
from vetted.mixins import OverallAdminMixin


class CompanyListView(OverallAdminMixin,ListView):
    """
    return: List of all the companies created by overall admin
    """
    model = Company
    paginate_by = 10


class CompanyCreateView(OverallAdminMixin, CreateView):
    """
    return: The view will create a company and will assign admin to it
    """
    model = Company
    form_class = CompanyForm

    def get_success_url(self):
        return reverse('company:list')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super(CompanyCreateView, self).form_valid(form)

class CompanyDeleteView(OverallAdminMixin, DeleteView):
    """
    return: The view will delete company requested by overalladmin
    """
    def get_object(self,*args,**kwargs):
        pk = self.kwargs["pk"]
        try:
            object = Company.objects.get(pk=pk)
        except:
            raise Http404
        return object

    def get_success_url(self):
        return reverse('company:list')

templates/company/company_base.html
{% extends "base.html" %}

templates/company/company_confirm_delete.html
  <form method="post" action="{% url 'company:delete' pk=company.pk %}">
            {% csrf_token %}
            <input type="submit"  class="btn btn-sm btn-danger" value="del">
        </form>

templates/company/company_form.html
{% extends "company/company_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h4>Create a company</h4>
   <form method="post" action="{% url 'company:add' %}">
       {% csrf_token %}
{{form | crispy }}
       <input type="submit" class="btn btn-sm">
       </form>

{% endblock %}

templates/company/company_list.html
{% extends "company/company_base.html" %}

{% block content %}


<div class="row">
    <div class="col-lg-3">
        <b>Company Name</b>
    </div>
    <div class="col-lg-3">
        <b>Domain</b>
    </div>
    <div class="col-lg-3">
        <b>Admin</b>
    </div>
    <div class="col-lg-3">
       <b>Delete</b>
    </div>
</div>

<div class="row">
    &nbsp;
</div>

{% for company in object_list %}

<div class="row">
    <div class="col-lg-3">
        {{company.name | upper}}
    </div>
    <div class="col-lg-3">
        {{company.email_domain}}
    </div>
    <div class="col-lg-3">
        {{company.admin}}
    </div>
    <div class="col-lg-3">
        <form method="post" action="{% url 'company:delete' pk=company.pk %}">
            {% csrf_token %}
            <input type="submit"  class="btn btn-sm btn-danger" value="del">
        </form>

    </div>
</div>

    <div style="margin-top:10px;border-top: 1px dotted gray" class="row">
        &nbsp;
    </div>
{% endfor %}

<div class="row">

    {% include 'pagination.html' %}
</div>

{% endblock %}