company/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, re_path
from company import views

app_name = "company"
urlpatterns = [

    re_path(
       r'^list/$',
       views.CompanyListView.as_view(),
       name='list'
    ),

    # URL pattern for the UserUpdateView
    re_path(
        r'^add/$',
        views.CompanyCreateView.as_view(),
        name='add'
    ),

    re_path(
        r'^delete/(?P<pk>\d+)/$',
        views.CompanyDeleteView.as_view(),
        name='delete'
    ),


]

employee/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, re_path
from employee import views

app_name = "employee"
urlpatterns = [

    re_path(
       r'^list/$',
       views.EmployeeListView.as_view(),
       name='list'
    ),

    # URL pattern for the UserUpdateView
    re_path(
        r'^add/$',
        views.EmployeeCreateView.as_view(),
        name='add'
    ),

    re_path(
        r'^delete/(?P<pk>\d+)/$',
        views.EmployeeDeleteView.as_view(),
        name='delete'
    ),

   re_path(
        r'^~update/$',
        views.EmployeeProfileUpdateView.as_view(),
        name='profile_update'
    ),
    re_path(
        r'^me/$',
        views.EmployeeProfileDetailView.as_view(),
        name='profile_detail'
    ),
    re_path(
        r'^invite/$',
        views.InvitationCreateView.as_view(),
        name='invite'
    ),

]

vetted/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found
from .views import HomeView, DashboardView

urlpatterns = [
    path('',HomeView.as_view(),name="home"),
    path('dashboard',DashboardView.as_view(),name="dashboard"),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('u/', include("users.urls", namespace="users")),
    path('company/', include("company.urls", namespace="company")),
    path('employee/', include("employee.urls", namespace="employee")),

]

templates/base.html
{% load static %}
<html lang="en">
   <head>

       {% block meta %}
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">


       {% endblock meta %}
      <title>Vetted</title>
      <!-- Bootstrap core CSS -->
        {% block head_css %}
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
      <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
      <!-- Custom styles for this template -->
      <link href='{% static "css/custom.css" %}' rel="stylesheet">

       {% endblock %}

            {% block head_js %}
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
       <script src='{% static "js/custom.js" %}'> </script>
       {% endblock %}
   </head>
   <body>
      <header>
          {% block nav%}

         <nav  style="background-color:white" class="navbar navbar-expand navbar-dark">
            <div class="container">
               <a style="" class="navbar-brand" href="#">

               </a>
               <div class="collapse navbar-collapse" id="navbarsExample07">
                  <ul class="navbar-nav mr-auto">
                     <li class="nav-item active">
                        <H2><a href="{% url 'home' %}">VETTED</a></H2>
                     </li>
                  </ul>
                  <ul align="right" class="navbar-nav mr-auto">

                      {% if request.user.user_role == "1" %}
                        <li class="nav-item active">
                        <a class="nav-link" href="{% url 'company:list' %}"><span> companies </span></a>
                     </li>
                       <li class="nav-item active">
                        <a class="nav-link" href="{% url 'company:add' %}"><span> add &nbsp;<i class="fa fa-plus"></i></span></a>
                     </li>
                        {% elif request.user.user_role == "2" %}
                      <li class="nav-item active">
                        <a class="nav-link"><span style="color:gray"> {{user.company.name|upper}} ( {{request.user.company.email_domain}} ) </span></a>
                     </li>

                         <li class="nav-item active">
                        <a class="nav-link" href="{% url 'employee:list' %}"><span> employees </span></a>
                     </li>
                       <li class="nav-item active">
                        <a class="nav-link" href="{% url 'employee:add' %}"><span> add &nbsp;<i class="fa fa-plus"></i></span></a>
                     </li>
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url 'employee:invite' %}"><span> invite &nbsp;<i class="fa fa-envelope"></i></span></a>
                     </li>
                      {% elif request.user.user_role == "3" %}

                       <li class="nav-item active">
                        <a class="nav-link" href="{% url 'employee:profile_detail' %}"><span> me </span></a>
                     </li>
                      <li class="nav-item active">
                        <a class="nav-link" href="{% url 'employee:profile_update' %}"><span> profile &nbsp;<i class="fa fa-pen"></i></span></a>
                     </li>
                      {% endif %}
                       <li class="nav-item dropdown">

        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         {% if request.user.is_authenticated %}
          {{ request.user.username }}
            {% else %}
            login
            {% endif %}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
               {% if request.user.is_authenticated %}
            <a class="dropdown-item" href="{% url 'account_logout' %}">logout</a>
            {% else %}
          <a class="dropdown-item" href="{% url 'account_login' %}">login</a>
          <a class="dropdown-item" href="{% url 'account_signup' %}">signup</a>

            {% endif %}
        </div>
      </li>

                  </ul>

               </div>
            </div>
         </nav>
          {% endblock nav %}
      </header>

      {% block main %}

      <main role="main">


            {% block home %}
          <div class="container">
              <div class="margin3 row">
                  &nbsp;
              </div>
            {% block content %}

          {% endblock %}
              </div>
            {% endblock %}


      </main>
      {% endblock main %}

      {% block footer %}

      <footer class="container py-5">
          <div class="line"></div>
         <div class="row">
            <div class="col-12 col-md">
               &copy; 2017-2018
               <small class="d-block mb-3 text-muted">VETTED</small>
            </div>

         </div>
      </footer>

      {%  endblock footer %}


   </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}


<div class="row">
    <div class="col-lg-6">

    </div>
</div>
<div class="row">
    &nbsp;
</div>

<div class="row">
    <div class="col-lg-6">
        <div style="display:none">
            {% for message in messages %}
<span style="color:green">{{message}}</span>
{% endfor %}
        </div>
{% if request.user.is_authenticated %}
        {% if request.user.user_role %}
         <h3>Welcome {{request.user.username}} to vetted !!!</h3>
        {% else %}

        <h4><i>No roles has been assigned yet</i></h4>

        {% endif %}
{% else %}

     <h4>Employee Management Suite</h4>

{% endif %}

    </div>
</div>

{% endblock %}

templates/pagination.html
{% if is_paginated %}


 <ul class="pagination">
  <li class="page-item">


      {% if page_obj.has_previous %}
      <a class="page-link previous" href="?page={{ page_obj.previous_page_number }}">
        &laquo;
      </a>
    {% else %}
      <span class="page-link previous">&laquo;</span>
    {% endif %}
  </li>

  {% for page_number in paginator.page_range %}
    {% if page_number == page_obj.number %}
        {% if page_obj.has_previous %}

            {% if page_number != page_obj.paginator.start_page %}

                 <li class="page-item">
                     <a class="page-link" href="?page=1">
                1</a>
                 </li>


            {% endif %}

            {% if page_number != 2 %}
                <li class="page-item"><span class="page-link">...</span></li>

            <li class="page-item" >
             <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                {{ page_obj.previous_page_number }} </a>
          </li>
            {% endif %}


           {% endif %}

      <li class="page-item active" >
        <span class="page-link">{{ page_number }}</span>
      </li>

        {% if page_obj.has_next %}
            {% if  page_obj.next_page_number != page_obj.paginator.num_pages %}
            <li class="page-item" >
             <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                {{ page_obj.next_page_number }} </a>
          </li>
                <li class="page-item"><span class="page-link">...</span></li>
            {% endif %}

             {% if page_number != page_obj.paginator.num_pages %}

                 <li class="page-item">
                     <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                {{ page_obj.paginator.num_pages }} </a>
                 </li>
            {% endif %}

         {% endif %}



      {% endif  %}

  {% endfor %}


  <li class="page-item">
    {% if page_obj.has_next %}
      <a class="page-link next" href="?page={{ page_obj.next_page_number }}">
        &raquo;
      </a>
    {% else %}
      <span class="page-link next">&raquo;</span>
    {% endif %}
  </li>
</ul>

    {% endif %}